(venv) PS C:\Users\manik\Downloads\sudoku-game-main\sudoku> flask db upgrade
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\manik\Downloads\sudoku-game-main\sudoku\venv\Scripts\flask.exe\__main__.py", line 7, in <module>
  File "C:\Users\manik\Downloads\sudoku-game-main\sudoku\venv\Lib\site-packages\flask\cli.py", line 1129, in main
    cli.main()
  File "C:\Users\manik\Downloads\sudoku-game-main\sudoku\venv\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\manik\Downloads\sudoku-game-main\sudoku\venv\Lib\site-packages\click\core.py", line 1682, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manik\Downloads\sudoku-game-main\sudoku\venv\Lib\site-packages\click\core.py", line 1729, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manik\Downloads\sudoku-game-main\sudoku\venv\Lib\site-packages\flask\cli.py", line 631, in get_command
    app = info.load_app()
          ^^^^^^^^^^^^^^^
  File "C:\Users\manik\Downloads\sudoku-game-main\sudoku\venv\Lib\site-packages\flask\cli.py", line 353, in load_app
    app = locate_app(import_name, None, raise_if_not_found=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manik\Downloads\sudoku-game-main\sudoku\venv\Lib\site-packages\flask\cli.py", line 245, in locate_app
    __import__(module_name)
  File "C:\Users\manik\Downloads\sudoku-game-main\sudoku\app.py", line 18, in <module>       
    db.init_app(app)
  File "C:\Users\manik\Downloads\sudoku-game-main\sudoku\venv\Lib\site-packages\flask_sqlalchemy\extension.py", line 355, in init_app
    raise RuntimeError(
RuntimeError: Either 'SQLALCHEMY_DATABASE_URI' or 'SQLALCHEMY_BINDS' must be set.